"""empty message

Revision ID: e675e41ca31b
Revises: 91d96ba738f7
Create Date: 2020-04-18 10:54:59.166809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e675e41ca31b'
down_revision = '91d96ba738f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('role', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'role')
    # ### end Alembic commands ###
