"""empty message

Revision ID: ef65e3fb357c
Revises: 8303424e492b
Create Date: 2020-04-20 11:02:18.690546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef65e3fb357c'
down_revision = '8303424e492b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('title', sa.String(length=200), nullable=False))
    op.drop_column('course', 'text')
    op.drop_column('course', 'video_url')
    op.drop_column('course', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('course', sa.Column('video_url', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('course', sa.Column('text', mysql.TEXT(), nullable=False))
    op.drop_column('course', 'title')
    # ### end Alembic commands ###
